# DataTable.toml

# 数据加载方式 0-从字节文件中加载,1-从json文件中加载
data_read_type = 0

# 数据字节文件地址
binary_path = 'Assets/Hotfix/Res/DataTable/Binary'

# 数据json文件地址
json_path = 'Assets/Hotfix/Res/DataTable/Json'

# 热更程序集名称
assembly_name = 'HotfixScripts'