# Download.toml

# 单次下载长度(分段下载,单次下载容量)
each_bytes_length = 134217728			 # 8 * 1024 * 1024 * 16 = 134217728 比特,即16M

# timeout 时长(单位: s, 浮点数), 持续该时长没有收到数据视为下载中断
timeout = 5

# 下载中断重新请求次数, 重新请求后仍然没有收到数据视为下载失败
repeated_time = 3