# Resource.toml

# 资源清单文件地址
manifest_path = "Hotfix/Res/manifest.txt"
# 资源清单名称和地址分隔符
manifest_split_symbol = "*"

# 资源加载类型: 0: 从远端下载AB包, 1: 从本地(StreamingAssets文件夹下)加载AB包, 2:从本地加载资源(Editor开发模式)
resource_load_type = 2

# 远端AB资源加载配置
[RemoteAB]
remote_version_path = "" # 版本文件地址
remote_AB_directory_path = "" # AB资源文件夹地址
local_version_path = "ABFiles/version.txt" # 本地存储版本文件地址
local_AB_directory_path = "ABFiles/Files" # 本地AB资源文件夹地址

# 本地AB资源加载配置
[LocalAB]


# Editor资源配置
